Contextual-Zephyr-KTO-b001-pos-undes0: # this should be the same as the name as the current directory
  prompt_template: "Contextual-Zephyr-KTO-b001-pos-undes0/prompt.txt"
  fn_completions: "vllm_local_completions"
  completions_kwargs:
    model_name: "/data/models/archangel/zephyr_sft_kto_pos_undesirableweight0_b001/LATEST/"
    model_kwargs:
      torch_dtype: 'bfloat16'
      tokenizer_mode: "auto"
      trust_remote_code: True
      tp: 2
    max_new_tokens: 2048
    # gpu_memory_utilization: 0.95
    temperature: 0.5
    top_p: 0.95
    batch_size: 900
  pretty_name: "Contextual AI (KTO-Zephyr Pos Only beta=0.01 UD=0) temp07" # name in the leaderboard
