# Contextual-KTO-Mistral-PairRM-temp07-hf: # this should be the same as the name as the current directory
  # prompt_template: "Contextual-KTO-Mistral-PairRM-temp07-hf/prompt.txt"
  # fn_completions: "vllm_local_completions"
  # completions_kwargs:
  #   model_name: "ContextualAI/Contextual_KTO_Mistral_PairRM"
  #   model_kwargs:
  #     torch_dtype: 'bfloat16'
  #     tokenizer_mode: "auto"
  #     trust_remote_code: True
  #   max_new_tokens: 2048
  #   temperature: 0.7
  #   top_p: 0.95
  #   batch_size: 900
  # pretty_name: "Contextual AI (KTO-Mistral-PairRM) temp07 v5" # name in the leaderboard
  # link: "https://huggingface.co/ContextualAI/Contextual_KTO_Mistral_PairRM hf" # link to the model's repo/information in the leaderboard

Contextual-KTO-Mistral-PairRM-Verified-v2:
  prompt_template: "Contextual-KTO-Mistral-PairRM-Verified-v2/prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "ContextualAI/Contextual_KTO_Mistral_PairRM"
    requires_chatml: True
    temperature: 0.7
    num_procs: 8
    is_strip: False
    max_tokens: 2048
    top_p: 0.95
    client_kwargs:
      base_url: "https://vr74xanx2jimu6ae.us-east-1.aws.endpoints.huggingface.cloud/v1/" #  "http://api.01ww.xyz/v1"
      #api_key: "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"
  pretty_name: "sm-Contextual-KTO-Mistral-PairRM-Verified"
  link: "https://huggingface.co/ContextualAI/Contextual_KTO_Mistral_PairRM" # link to the model's repo/information in the leaderboard


# Contextual-KTO-Mistral-PairRM-Verified:
#   prompt_template: "Contextual-KTO-Mistral-PairRM-Verified/prompt.txt"
#   fn_completions: "huggingface_api_completions"
#   completions_kwargs:
#     model_name: "https://vr74xanx2jimu6ae.us-east-1.aws.endpoints.huggingface.cloud/v1/" # "ContextualAI/Contextual_KTO_Mistral_PairRM"
#     max_new_tokens: 50
#     temperature: 0.7
#     top_p: 0.95
#     #is_fast_tokenizer: False # needed for local
#   # completion_parser_kwargs:
#   #   outputs_to_match:
#   #     1: '(?:^|\n) ?Output \(a\)'
#   #     2: '(?:^|\n) ?Output \(b\)'
#   batch_size: 1
#   pretty_name: "Contextual-KTO-Mistral-PairRM-Verified"
#   link: "https://huggingface.co/ContextualAI/Contextual_KTO_Mistral_PairRM hf" # link to the model's repo/information in the leaderboard