Contextual-ZephyrSFTBeta-KTOInfo: # this should be the same as the name as the current directory
  prompt_template: "Contextual-ZephyrSFTBeta-KTOInfo/prompt.txt"
  fn_completions: "vllm_local_completions"
  completions_kwargs:
    model_name: "/data/models/archangel/kto-info_zephyr-sft-beta_ultrabin_b0.1/LATEST" 
    model_kwargs:
      torch_dtype: 'bfloat16'
      tokenizer_mode: "auto"
      trust_remote_code: True
      tp: 2
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 0.95
    batch_size: 900
  pretty_name: "Contextual AI (KTO Zephyr SFT ultrabin) temp07"
