Contextual-Mixtral-KTO-PairRM-iter3: # this should be the same as the name as the current directory
  prompt_template: "Contextual-Mixtral-KTO-PairRM-iter3/prompt.txt"
  fn_completions: "vllm_local_completions"
  completions_kwargs:
    model_name: "/data/models/archangel/zephyr_sft_kto-logsigmoid" # "ContextualAI/Contextual-Mixtral-KTO-PairRM-iter3"
    model_kwargs:
      torch_dtype: 'bfloat16'
      tokenizer_mode: "auto"
      trust_remote_code: True
      tp: 2
    max_new_tokens: 2048
    # gpu_memory_utilization: 0.95
    temperature: 0.7
    top_p: 0.95
    batch_size: 900
  pretty_name: "Contextual AI (KTO-Zephyr-logsigmoid) temp07" # name in the leaderboard
